version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nwscore-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nwscore-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin123
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - dev

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nwscore-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy && node dist/main"

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: nwscore-network 